---
# Install and setup essential utilities for laptop
# - GUI version applications
# - Entertainment applications
#
# Requisites:
# Install Roles
#
# cd <directory_contains_requirements.yml>
# ansible-galaxy install -r requirements-laptop.yml
#
# Execute command:
# ansible-playbook laptop.yml --ask-sudo-pass
#
- hosts: laptop
  become: true
  vars:
    emacs_build_ver: '26.1'
    emacs_build_options: ''
  roles:
    # - role: edunonnn.desktop-extra
    # - role: edunonnn.spotify
    # - role: edunonnn.skypeforlinux
    # - { role: cmprescott.chrome, become: yes }

    # TODO: adds dependencies: libx11-dev and others
    # - role: edunonnn.emacs-build
    #   emacs_install_dir: '/usr/local/stow/emacs-{{ emacs_build_ver }}'
    # - role: edunonnn.stow-install-package
    #   stow_install_package: 'emacs-{{ emacs_build_ver }}'
    - role: edunonnn.zsh
      zsh_ohmy_theme: bira
      zsh_ohmy_plugins:
        - git
        - gitfast
        - git-extras
        - zsh-syntax-highlighting
        - zsh-autosuggestions
        - history-substring-search
    - role: trinitronx.tmux
