---
# Install Packages:
# shutter: Screen Capture
# Dropbox
#
# Execute command:
# ansible-playbook work-misc-utils.yml -vvv --ask-sudo-pass
#
- name: Setup miscellaneous utilities for my work environment
  hosts: x230-i5
  sudo: True
  tasks:
    - name: Install screen capture packages
      apt: name=shutter update_cache=yes

    - name: Install Dropbox
      # cd ~ && wget -O - "https://www.dropbox.com/download?plat=lnx.x86_64" | tar xzf -
      unarchive:
        src: https://www.dropbox.com/download?plat=lnx.x86_64
        dest: ~/
        remote_src: True
      become_user: nonnn
