---
# Install Packages:
# shutter: Screen Capture
# Dropbox
#
# Execute command:
# ansible-playbook work-misc-utils.yml -vvv --ask-sudo-pass
#
- name: Setup miscellaneous utilities for my work environment
  hosts: x230-i5
  become: true
  tasks:
    - name: Install screen capture packages
      apt: name=shutter update_cache=yes

    - name: Install Dropbox
      # cd ~ && wget -O - "https://www.dropbox.com/download?plat=lnx.x86_64" | tar xzf -
      unarchive:
        src: https://www.dropbox.com/download?plat=lnx.x86_64
        dest: ~/
        remote_src: True
      become_user: nonnn

    - name: Install Audacity
      apt: name=audacity update_cache=yes

    - name: Get Smart Scope deb package
      command: wget --trust-server-names https://www.lab-nation.com/package/smartscope/linux/latest/get -O /tmp/SmartScope-Linux.deb
      become_user: nonnn

    - name: Install Smart Scope
      apt:
        deb: /tmp/SmartScope-Linux.deb

    - name: Install screen capture packages
      apt: name=okular update_cache=yes
