---
#
# Execute command:
# ansible-playbook work-console-utils.yml -vvv --ask-sudo-pass
#
- name: Setup Console utilities
  hosts: x230-i5
  become: true
  vars:
    ser2net_conf_file: /etc/ser2net.conf
  tasks:
    - name: Install console packages
      apt: name=ser2net update_cache=yes # redirect serial port to telnet

    - name: Copy ser2net config file
      copy: src=files/ser2net.conf dest={{ ser2net_conf_file }} owner=root mode=600
      # notify: restart ser2net # See the example

    - name: Restart ser2net
      service: name=ser2net state=restarted

  #
  # Here is just an example for Ansible module 'notify' and 'handlers'
  #
  # The 'handlers' will execute only once after all tasks finished
  # And the execution order is 'handlers' in playbook not 'notify'
  #
  # The suggestion not to use 'handlers' for simple job
  #
  # handlers:
  #   - name: restart ser2net
  #     service: name=ser2net state=restarted
