---
#
# Execute command:
# ansible-playbook work-tweak-ubuntu.yml -vvv --ask-sudo-pass
#
- name: Tweak Ubuntu for my work environment
  hosts: x230-i5
  sudo: True
  tasks:
    - name: Adjust Unity HUD size
      command: dbus-launch gsettings set org.compiz.unityshell:/org/compiz/profiles/unity/plugins/unityshell/ icon-size 32
      become_user: nonnn

    # FIXME:
    # This action is not working. Because it should get DBUS_SESSION_BUS_ADDRESS
    # to execute command with exist dbus session
    - name: Disable ALT key to show HUD
      command: dbus-launch --exit-with-session gsettings set org.compiz.integrated show-hud "['disabled']"
      become_user: nonnn

    # Manual Steps:
    # CompizConfig Settings -> Unity Ubuntu Plugin -> Desktop -> Ubuntu Unity Plugin"
    # 1. Clean "Key to show the menu bar while pressed"
    # 2. Clean "Key to show the HUD when tapped"
    - name: Disable ALT key to show menu bar
      apt: name=compizconfig-settings-manager update_cache=yes

    - name: Install Chinese fonts
      apt:
        name:
          - fonts-arphic-ukai
          - fonts-arphic-uming
          - fonts-droid-fallback
        update_cache: yes

    # Manual Steps:
    # System Settings -> Language Support ->
    # 1. change input method to 'fcitx'
    # 2. Install 'Chinese' and Apply then Re-login
    # 3. On top of menu bar -> keyboard icon (fcitx) -> Configuration
    #    -> Input Method -> Liu
    - name: Install Chinese input
      apt:
        name:
          - fcitx
          - fcitx-table-boshiamy
        update_cache: yes

    # Manual Steps:
    # gnome-control-center -> online accounts -> Add account Google
    - name: Sync. with Google Drive
      apt:
        name:
          - gnome-control-center
          - gnome-online-accounts
        update_cache: yes
