---
# Install Packages:
# shutter: Screen Capture
#
# Execute command:
# ansible-playbook work-misc-utils.yml -vvv --ask-sudo-pass
#
- name: Setup miscellaneous utilities for my work environment
  hosts: x230-i5
  become: true
  tasks:
    - name: Install screen capture packages
      apt: name=shutter update_cache=yes

    - name: Install Audacity
      apt: name=audacity update_cache=yes

    - name: Get Smart Scope deb package
      command: wget --trust-server-names https://www.lab-nation.com/package/smartscope/linux/latest/get -O /tmp/SmartScope-Linux.deb
      become_user: nonnn

    - name: Install Smart Scope
      apt:
        deb: /tmp/SmartScope-Linux.deb

    - name: Install PDF editor packages
      apt: name=okular update_cache=yes
