---
# Install Packages:
# ansible
# virtualbox
#
# Execute command:
# ansible-playbook work-ci-utils.yml -vvv --ask-sudo-pass
#
- name: Setup CI(Continuous Integration) utilities
  hosts: x230-i5
  sudo: True
  tasks:
    - name: Install required packages
      apt:
        name:
          - python-pip
          - libssl-dev
        update_cache: yes

    - name: Install ansible
      pip:
        name: ansible

    # VirtualBox
    - name: Add VirtualBox repository
      apt_repository:
        repo: "deb http://download.virtualbox.org/virtualbox/debian xenial contrib"

    - name: Add VirtualBox secure key
      apt_key:
        url: "https://www.virtualbox.org/download/oracle_vbox.asc"

    - name: Install VirtualBox
      apt:
        name: virtualbox-5.1
        update_cache: yes

    # Vagrant
    - name: Download Vagrant
      get_url:
        url: https://releases.hashicorp.com/vagrant/1.9.7/vagrant_1.9.7_x86_64.deb
        dest: /tmp/vagrant.deb

    - name: Install Vagrant
      apt: deb=/tmp/vagrant.deb
