---
# tasks file for work-essential
  - name: Install essential packages
    apt:
      name:
        - build-essential
        - vim
        - stow # stow is local built package management
        - tree
        - htop
        - git
        - git-extras
      update_cache: yes
